// bblogv3/src/pages/write.tsx
import { uploadImage } from "@/ajax/ajax";
import useInput from "@/hooks/useInput";
import { AppDispatch } from "@/store/store";
import { Button, Flex, Input, Menu, MenuButton, MenuItem, MenuList, Select, Text } from "@chakra-ui/react";
import { Highlight } from "@tiptap/extension-highlight";
import Image from "@tiptap/extension-image";
import Link from "@tiptap/extension-link";
import Placeholder from "@tiptap/extension-placeholder";
import TextAlign from "@tiptap/extension-text-align";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import { useRouter } from "next/router";
import { ChangeEvent, useRef, useState } from "react";
import { useDispatch } from "react-redux";
import { Icon } from "@iconify/react";
import DelTags from "@/component/article/deletableTags";
import { t } from "i18next";
const Write = () => {
    const router = useRouter();
    const OptionsText = ["INTRO", "FRONTEND", "BACKEND", "ETC", "PORTFOLIO"];
    const imgBox = useRef<HTMLInputElement>(null);
    const [hash, hashOnChange, setHash] = useInput();
    const [options, optionsOnChange, setOptions] = useInput();
    const [hide, hideOnChange, setHide] = useInput();
    const [title, titleOnChange, setTitle] = useInput();
    const [taglist, setTagList] = useState<string[]>([]);
    const [start, startOnChange, setStart] = useInput();
    const [end, endOnChange, setEnd] = useInput();
    const [github, githubOnChange, setGithub] = useInput();
    const [published, publishedOnChange, setPublished] = useInput();
    const [uploadedImg, setUploadedImg] = useState<string[]>([]);
    const [thumbnail, setThumbtail] = useState<string>("");
    const [tag, onChangeTag, setTag] = useInput();
    const dispatch = useDispatch<AppDispatch>();
    const editor = useEditor({
        extensions: [
            StarterKit.configure({
                heading: {
                    levels: [1, 2, 3],
                },
            }),
            TextAlign.configure({
                types: ["heading", "paragraph"],
            }),
            Image.configure({
                inline: true,
            }),
            Highlight.configure({ multicolor: true }),
            Link.configure({
                autolink: true,
                openOnClick: true,
                linkOnPaste: true,
            }),
            Placeholder.configure({
                placeholder: "내용",
            }),
        ],
        content: "",
    });

    if (!editor) {
        return null;
    }

    const imgUpload = (e: ChangeEvent<HTMLInputElement>) => {
        let formData = new FormData();
        if (e.target.files) {
            formData.append("upload", e.target.files[0]);
            dispatch(uploadImage(formData)).then((res) => {
                setThumbtail(`https://hyns.dev/v1/image/` + res);
                editor
                    .chain()
                    .focus()
                    .setImage({ src: `/v1/image/` + res.payload, alt: "bblog img" })
                    .run();
            });
        }
    };

    const alignment = (which: string) => {
        editor.chain().focus().setTextAlign(which).run();
    };
    const bold = () => {
        editor.chain().focus().toggleBold().run();
    };
    const strike = () => {
        editor.chain().focus().toggleStrike().run();
    };
    const bullet = () => {
        editor.chain().focus().toggleBulletList().run();
    };
    const orderlist = () => {
        editor.chain().focus().toggleOrderedList().run();
    };
    const codeblock = () => {
        editor.chain().focus().toggleCodeBlock().run();
    };
    const clearAll = () => {
        editor.chain().focus().clearNodes().run();
        editor.chain().focus().unsetAllMarks().run();
        editor.chain().focus().unsetTextAlign().run();
    };
    const redo = () => {
        editor.chain().focus().redo().run();
    };
    const undo = () => {
        editor.chain().focus().undo().run();
    };

    const highlight = () => {
        editor?.chain().focus().toggleHighlight().run();
    };

    const heading = (i: number) => {
        switch (i) {
            case 0:
                editor.chain().focus().toggleHeading({ level: 1 }).run();
                return;
            case 1:
                editor.chain().focus().toggleHeading({ level: 2 }).run();
                return;
            case 2:
                editor.chain().focus().toggleHeading({ level: 3 }).run();
                return;
            case 3:
                editor.chain().focus().toggleHeading({ level: 4 }).run();
                return;
            default:
                break;
        }
    };

    const delTags = (tag: string) => {
        setTagList(() => [...taglist].filter((v) => v != tag));
    };

    const setFilteredTag = (e: Event) => {
        e.preventDefault;
        console.log(tag);
    };

    return (
        <Flex w="full" direction={"column"} gap={2}>
            <form className="p-0 m-0">
                <Input value={title} onChange={titleOnChange} className="custom-input2" borderWidth={1} type="text" p="2" h={"3.5rem"} />
            </form>
            <Flex className="text-3xl custom-input2 p-3" justify={"space-between"}>
                <Icon icon="mdi:undo" onClick={() => undo()} />
                <Icon icon="mdi:redo" onClick={() => redo()} />
                <Menu>
                    <MenuButton>
                        <Icon icon="bx:heading" />
                    </MenuButton>
                    <MenuList borderWidth={0} minW={"30px"} p={0}>
                        {Array.from({ length: 3 }).map((v, index) => {
                            return (
                                <MenuItem key={index} onClick={() => heading(index)}>
                                    H{index + 1}
                                </MenuItem>
                            );
                        })}
                    </MenuList>
                </Menu>
                <Icon icon="ri:underline" onClick={() => highlight()} />
                <Icon icon="material-symbols:format-bold" onClick={() => bold()} />
                <Icon icon="gg:format-strike" onClick={() => strike()} />
                <Icon icon="bx:list-ul" onClick={() => bullet()} />
                <Icon icon="bx:list-ol" onClick={() => orderlist} />
                <Icon icon="material-symbols:format-align-left" onClick={() => alignment("left")} />
                <Icon icon="material-symbols:format-align-center" onClick={() => alignment("center")} />
                <Icon icon="material-symbols:format-align-right" onClick={() => alignment("right")} />
                <Icon icon="material-symbols:code-rounded" onClick={() => codeblock()} />
                <Icon icon="ph:eraser-duotone" onClick={() => clearAll()} />

                <Icon icon="material-symbols:image-outline-sharp" onClick={() => imgBox.current?.click()} />
            </Flex>

            <section className="custom-input2">
                <EditorContent className="p-3" editor={editor} />
            </section>
            <form className="invisible w-0 h-0">
                <input type="file" ref={imgBox} id="img" className="invisible w-0 h-0" onChange={(e) => imgUpload(e)} />
            </form>

            <section className="tag w-full h-full">
                <div className="p-3 bg-slate-300 dark:bg-slate-500 flex flex-wrap gap-3 items-center">
                    <Icon icon="mdi:tag" className="translate-y-[0.125rem]" />
                    <DelTags tags={taglist} delTags={delTags} />
                    <form
                        className="taginput flex items-center translate-y-[0.1rem]"
                        onSubmit={(e) => {
                            e.preventDefault();
                        }}
                    >
                        <label htmlFor="tagInput" className="-translate-y-[1px]">
                            <Icon icon="mdi:pencil" className="translate-y-[0.1rem]" />
                        </label>
                        <input id="tagInput" type="text" placeholder={t("enter_tag")!} value={tag} onChange={onChangeTag} className="h-7 bg-transparent outline-none border-0 focus:ring-transparent shadow-none px-1" />
                    </form>
                </div>
            </section>
            <Flex flexDirection={"column"} gap={2}>
                <Flex alignItems={"center"} gap={5} width={"50%"}>
                    <Input size="sm" borderRadius={0} type="date" value={start} onChange={startOnChange} />
                    <Text>~</Text>
                    <Input size="sm" borderRadius={0} type="date" value={end} onChange={endOnChange} />
                </Flex>
                <Input size="sm" placeholder="깃허브" borderRadius={0} type="text" value={github} onChange={githubOnChange} width={"50%"} />
                <Input size="sm" placeholder="배포 사이트" borderRadius={0} type="text" value={published} onChange={publishedOnChange} width={"50%"} />
            </Flex>

            <Flex gap={2} justifyContent={"flex-end"}>
                <Select placeholder="공개 설정" padding={0} borderRadius={0} borderColor={'transparent'} value={hide} onChange={hideOnChange} width={"30%"} maxW={"130px"}>
                    <option value="0">공개</option>
                    <option value="1">비공개</option>
                </Select>
                <Button
                    borderWidth={1}
                    borderRadius={0}
                    //  onClick={writeArticle}
                >
                    {/* {aid ? "수정" : "등록"} */}
                    수정
                </Button>
            </Flex>
        </Flex>
    );
};

export default Write;

// bblogfront/src/views/Write/Write.vue
<template>
    <div class="write d-flex flex-column justify-content-center pt-5 align-items-center gap-3 h-100">
        <div class="category"></div>
        <div class="write-title w-50">
            <input type="text" name="title" v-model="articleState.title" placeholder="제목" class="w-100 h-100 p-1 px-2" />
        </div>
        <div class="editor w-50">
            <div class="editor-btns">
                <button class="bi bi-arrow-left" @click="undo" :disabled="!editor?.can().chain().focus().undo().run()"></button>
                <button class="bi bi-arrow-right" @click="redo" :disabled="!editor?.can().chain().focus().redo().run()"></button>
                <button class="bi bi-justify-left" @click="alignment('left')"></button>
                <button class="bi bi-justify" @click="alignment('center')"></button>
                <button class="bi bi-justify-right" @click="alignment('right')"></button>
                <button class="bi bi-type-bold" @click="bold"></button>
                <button class="bi bi-type-strikethrough" @click="strike"></button>
                <label class="bi bi-image" for="imgup"><input id="imgup" type="file" class="filebox" ref="imgBox" @change="imgUpload" /></label>
                <button class="bi bi-brightness-high" @click="highlight"></button>
                <button class="bi bi-code" @click="code"></button>
                <button class="bi bi-list-task" @click="bullet"></button>
                <button class="bi bi-list-ol" @click="orderlist"></button>
                <button class="bi bi-file-earmark-code" @click="codeblock"></button>
                <button class="bi bi-stars" @click="clearAll"></button>
            </div>
            <editor-content :editor="editor" class="editor-description" />
        </div>
        <input type="text" v-model="hashStates.tag" v-on:keyup.space="makingTag" placeholder="태그" class="p-1 px-2 w-50" />
        <div class="hashtags w-50 d-flex overflow-auto">
            <div class="tag d-flex justify-content-center align-items-center text-nowrap" v-for="(item, i) in articleState.tags" :key="item">
                <span class="m-1"># {{ item }}</span>
                <button class="delbtn d-flex justify-content-center align-items-center px-1">
                    <span v-on:click="deleteTag(i)" class="bi bi-x-lg"></span>
                </button>
            </div>
        </div>
        <div class="d-flex justify-content-end w-50">
            <ul class="list-group list-group-horizontal align-items-center gap-3">
                <li class="list-group-item border border-0 p-0">
                    <div class="tagwarning" v-html="hashStates.warning"></div>
                </li>
                <li class="list-group-item border border-0 p-0">
                    <select class="form-select form-select-sm" v-model="articleState.category" aria-label=".form-select-sm">
                        <option value="0">카테고리</option>
                        <option value="1" v-for="i in 5" :key="i">더미{{ i }}</option>
                    </select>
                </li>
                <li class="list-group-item border border-0 p-0 d-flex gap-1">
                    <select class="form-select form-select-sm" v-model="articleState.hide" aria-label=".form-select-sm">
                        <option value="0">공개</option>
                        <option value="1">비공개</option>
                    </select>
                </li>

                <li class="list-group-item border border-0 p-0">
                    <span class="border border-1 p-2 px-3 submit" @click="write">등록</span>
                </li>
            </ul>
        </div>
    </div>
</template>
<script setup lang="ts">
    import { useEditor, EditorContent } from "@tiptap/vue-3";
    import TextAlign from "@tiptap/extension-text-align";
    import StarterKit from "@tiptap/starter-kit";
    import Image from "@tiptap/extension-image";
    import Link from "@tiptap/extension-link";
    import { Highlight } from "@tiptap/extension-highlight";
    import { reactive, ref } from "vue";
    import axios from "@/store/axios";
    import router from "@/router";

    const imgBox = ref<HTMLInputElement>();

    const editor = useEditor({
        content: "",
        extensions: [
            StarterKit,
            TextAlign.configure({
                types: ["heading", "paragraph"],
            }),
            Image.configure({
                inline: true,
            }),
            Highlight.configure({ multicolor: true }),
            Link.configure({
                autolink: true,
                openOnClick: true,
                linkOnPaste: true,

            }),
        ],
    });

    const imgUpload = () => {
        let formData = new FormData();
        if (imgBox.value?.files) {
            formData.append("uploadimg", imgBox.value.files[0]);
        }
        axios.post("/article/admin/images/upload", formData).then((res) => {
            editor.value
                ?.chain()
                .focus()
                .setImage({ src: `./blogapi/article/images/${res.data}` })
                .run();
            articleState.image.push(JSON.parse(JSON.stringify(res.data)));
        });
    };

    const hashStates = reactive<{ warning?: string; tag?: string }>({
        warning: "",
        tag: "",
    });

    let articleState = reactive<{ title: string; tags?: string[]; category: number; hide: number; image: string[] }>({
        title: "",
        tags: [],
        category: 0,
        hide: 0,
        image: [],
    });

    const makingTag = () => {
        if (hashStates.tag?.trim().replace(/ /, "").length == 0) {
            hashStates.warning = "공백은 태그로 사용이 불가능합니다";
            hashStates.tag = "";
            return;
        }
        if (articleState.tags?.includes(hashStates.tag?.trim().replace(/ /, "") as string)) {
            hashStates.warning = "이미 등록된 태그입니다";
            hashStates.tag = "";
            return;
        }
        articleState.tags?.push(hashStates.tag?.trim().replace(/ /, "") as string);
        hashStates.warning = "";
        hashStates.tag = "";
    };

    const deleteTag = (i: number) => {
        articleState.tags?.splice(i, 1);
    };

    const alignment = (which: string) => {
        editor.value?.chain().focus().setTextAlign(which).run();
    };

    const bold = () => {
        editor.value?.chain().focus().toggleBold().run();
    };

    const strike = () => {
        editor.value?.chain().focus().toggleStrike().run();
    };

    const code = () => {
        editor.value?.chain().focus().toggleCode().run();
    };

    const bullet = () => {
        editor.value?.chain().focus().toggleBulletList().run();
    };

    const orderlist = () => {
        editor.value?.chain().focus().toggleOrderedList().run();
    };

    const codeblock = () => {
        editor.value?.chain().focus().toggleCodeBlock().run();
    };

    const clearAll = () => {
        editor.value?.chain().focus().clearNodes().run();
        editor.value?.chain().focus().unsetAllMarks().run();
        editor.value?.chain().focus().unsetTextAlign().run();
    };

    const redo = () => {
        editor.value?.chain().focus().redo().run();
    };

    const undo = () => {
        editor.value?.chain().focus().undo().run();
    };

    const highlight = () => {
        editor.value?.chain().focus().toggleHighlight().run();
    };

    const write = () => {
        if (articleState.category === 0) {
            hashStates.warning = "카테고리를 선택하세요";
            return;
        }
        if (editor.value?.getText().trim().length === 0) {
            hashStates.warning = "본문을 입력하세요";
            return;
        }
        const articlebody: { title: string; context: string | undefined; tags?: string[]; category: number; hide: boolean; menuid: number; image?: string[] } = {
            title: articleState.title,
            context: editor.value?.getHTML(),
            tags: articleState.tags,
            category: articleState.category,
            hide: articleState.hide === 0 ? false : true,
            menuid: articleState.category,
        };
        if (articleState.image.length > 0) {
            articlebody.image = articleState.image;
        }
        axios.post("/article/admin/write", articlebody).then((res) => router.push(`./read?id=${res.data}`));
    };
</script>
<style lang="sass">
    @import "Write.sass"
</style>
