// bblogfront/src/components/Header/Header.vue
<template>
    <div class="navcontainer">
        <ul class="list-group list-group-horizontal-md h-auto w-100 bg-black rounded-0 justify-content-between px-3">
            <router-link to="/"><li class="border border-0 list-group-item bg-black rounded-0 text-white d-flex align-items-center">Hyunseok</li></router-link>
            <div class="icon-section d-flex">
                <div class="icon-section-admin d-flex" v-if="store.userToken">
                    <router-link to="setting"><li class="border border-0 list-group-item bg-black rounded-0 text-white bi bi-gear"></li></router-link>
                    <router-link to="write"><li class="border border-0 list-group-item bg-black rounded-0 text-white bi bi-pencil"></li></router-link>
                </div>
                <div class="icon-section-common d-flex" >
                    <li class="border border-0 list-group-item bg-black rounded-0 text-white bi bi-list text-nowrap" data-bs-toggle="offcanvas" data-bs-target="#menubar" aria-controls="menubar"> Menu</li>
                    <a href="https://github.com/B-HS" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-custom-class="custom-tooltip" data-bs-title="깃허브">
                        <li class="border border-0 list-group-item bg-black rounded-0 text-white bi-github"></li>
                    </a>
                    <a href="https://hbyun.tistory.com/" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-custom-class="custom-tooltip" data-bs-title="티스토리">
                        <li class="border border-0 list-group-item bg-black rounded-0 text-white bi bi-bootstrap"></li>
                    </a>
                    <a href="https://portfolio.hyns.co.kr/" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-custom-class="custom-tooltip" data-bs-title="포트폴리오 사이트">
                        <li class="border border-0 list-group-item bg-black rounded-0 text-white bi bi-file-text"></li>
                    </a>
                    <router-link to="login" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-custom-class="custom-tooltip" data-bs-title="로그인">
                        <li class="border border-0 list-group-item bg-black rounded-0 text-white bi bi-box-arrow-in-right"></li>
                    </router-link>
                </div>
            </div>
        </ul>
        <section class="scrollstat w-100">
            <div class="scrollstat-bar" ref="statbar"></div>
        </section>
        <MenuBar></MenuBar>
    </div>
</template>
<script setup lang="ts">
    import { Tooltip } from "bootstrap";
    import { onMounted, ref } from "vue";
    import MenuBar from "../Menu/MenuBar.vue";
    import { useUserStore } from "@/store/userStore";
    const statbar = ref();
    new Tooltip(document.body, {
        selector: "[data-bs-toggle='tooltip']",
    });

    const store = useUserStore()

    

    onMounted(() => {
        window.onscroll = () => scrollbar();
        const scrollbar = () => {
            let winScroll = document.body.scrollTop || document.documentElement.scrollTop;
            let height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
            let scrolled = (winScroll / height) * 100;
            statbar.value.style.width = scrolled + "%";
        };
    });
</script>
<style lang="sass" scoped>
    @import "Header.sass"
</style>

// bblogfrontv2/src/Components/Header/Header.tsx
import { Tooltip } from "@chakra-ui/react";
import { useCallback, useEffect, useRef, useState } from "react";
import { BsBoxArrowRight, BsGithub } from "react-icons/bs";
import { TbLetterT } from "react-icons/tb";
import { Link } from "react-router-dom";

export const Header = () => {
    const [scrollWith, setScrollWith] = useState<number>(0);
    const [windowWidth, setWindowWidth] = useState<number>(0);
    const [currentLocation, setCurrentLocation] = useState<string>("");
    const verticalscroll = useRef<HTMLDivElement>(null);

    const scrollbar = useCallback(() => {
        let winScroll = document.body.scrollTop || document.documentElement.scrollTop;
        let height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
        setScrollWith((winScroll / height) * 100);
    }, [scrollWith]);
    const calcWith = useCallback(() => {
        return setWindowWidth(window.innerWidth);
    }, [windowWidth]);
    const fillColorMenu = useCallback(() => {
        return setCurrentLocation(window.location.href.split("/")[3]);
    }, [currentLocation]);

    const resetStatus = (name: string) => {
        window.scrollTo(0, 0);
        setScrollWith(0);
        setCurrentLocation(name);
    };

    useEffect(() => calcWith, []);
    useEffect(() => fillColorMenu, []);

    window.onscroll = () => scrollbar();
    window.onresize = () => calcWith();
    window.addEventListener("popstate", () => {
        setCurrentLocation(window.location.href.split("/")[3]);
    });

    return (
        <>
            <div className="header h-12 mx-[0.07rem] bg-white bg-opacity-50 text-black flex items-baseline justify-between sticky top-0 gap-2 text-lg z-50 transition ease-in-out duration-200 hover:bg-opacity-100 pt-2 px-3 border-b">
                <div className="main flex items-baseline gap-2">
                    <Link to="/">
                        <span className="text-2xl" onClick={() => resetStatus("")}>
                            Hyunseok
                        </span>
                    </Link>
                    <section className="menu whitespace-nowrap">
                        <Link to="/">
                            <span className={`text-sm ${currentLocation == "" ? "text-violet-500" : ""}`} onClick={() => resetStatus("")}>
                                소개
                            </span>
                        </Link>
                        <span className="text-sm"> | </span>
                        <Link to="/blog">
                            <span className={`text-sm ${currentLocation == "blog" ? "text-violet-500" : ""}`} onClick={() => resetStatus("blog")}>
                                블로그
                            </span>
                        </Link>
                        <span className="text-sm"> | </span>
                        <Link to="/portfolio">
                            <span className={`text-sm ${currentLocation == "portfolio" ? "text-violet-500" : ""}`} onClick={() => resetStatus("portfolio")}>
                                포트폴리오
                            </span>
                        </Link>
                    </section>
                </div>
                <div className="navigator flex gap-3">
                    <a href="https://github.com/B-HS">
                        <Tooltip label="깃허브" aria-label="gibhub" hasArrow arrowSize={10}>
                            <span>
                                <BsGithub />
                            </span>
                        </Tooltip>
                    </a>
                    <a href="https://hbyun.tistory.com/">
                        <Tooltip label="티스토리" aria-label="tistory" hasArrow arrowSize={10}>
                            <span>
                                <TbLetterT />
                            </span>
                        </Tooltip>
                    </a>
                    <a href="/login">
                        <Tooltip label="로그인" aria-label="login" hasArrow arrowSize={10}>
                            <span>
                                <BsBoxArrowRight />
                            </span>
                        </Tooltip>
                    </a>
                </div>
            </div>
            <div ref={verticalscroll} className={`bg-black z-50 h-1 sticky top-12 overflow-hidden w-[${scrollWith}%]`} style={{ width: `${scrollWith}%` }}></div>
        </>
    );
};
