// bblogfront/src/views/Write/Write.vue
<template>
    <div class="write d-flex flex-column justify-content-center pt-5 align-items-center gap-3 h-100">
        <div class="category"></div>
        <div class="write-title w-50">
            <input type="text" name="title" v-model="articleState.title" placeholder="제목" class="w-100 h-100 p-1 px-2" />
        </div>
        <div class="editor w-50">
            <div class="editor-btns">
                <button class="bi bi-arrow-left" @click="undo" :disabled="!editor?.can().chain().focus().undo().run()"></button>
                <button class="bi bi-arrow-right" @click="redo" :disabled="!editor?.can().chain().focus().redo().run()"></button>
                <button class="bi bi-justify-left" @click="alignment('left')"></button>
                <button class="bi bi-justify" @click="alignment('center')"></button>
                <button class="bi bi-justify-right" @click="alignment('right')"></button>
                <button class="bi bi-type-bold" @click="bold"></button>
                <button class="bi bi-type-strikethrough" @click="strike"></button>
                <label class="bi bi-image" for="imgup"><input id="imgup" type="file" class="filebox" ref="imgBox" @change="imgUpload" /></label>
                <button class="bi bi-brightness-high" @click="highlight"></button>
                <button class="bi bi-code" @click="code"></button>
                <button class="bi bi-list-task" @click="bullet"></button>
                <button class="bi bi-list-ol" @click="orderlist"></button>
                <button class="bi bi-file-earmark-code" @click="codeblock"></button>
                <button class="bi bi-stars" @click="clearAll"></button>
            </div>
            <editor-content :editor="editor" class="editor-description" />
        </div>
        <input type="text" v-model="hashStates.tag" v-on:keyup.space="makingTag" placeholder="태그" class="p-1 px-2 w-50" />
        <div class="hashtags w-50 d-flex overflow-auto">
            <div class="tag d-flex justify-content-center align-items-center text-nowrap" v-for="(item, i) in articleState.tags" :key="item">
                <span class="m-1"># {{ item }}</span>
                <button class="delbtn d-flex justify-content-center align-items-center px-1">
                    <span v-on:click="deleteTag(i)" class="bi bi-x-lg"></span>
                </button>
            </div>
        </div>
        <div class="d-flex justify-content-end w-50">
            <ul class="list-group list-group-horizontal align-items-center gap-3">
                <li class="list-group-item border border-0 p-0">
                    <div class="tagwarning" v-html="hashStates.warning"></div>
                </li>
                <li class="list-group-item border border-0 p-0">
                    <select class="form-select form-select-sm" v-model="articleState.category" aria-label=".form-select-sm">
                        <option value="0">카테고리</option>
                        <option value="1" v-for="i in 5" :key="i">더미{{ i }}</option>
                    </select>
                </li>
                <li class="list-group-item border border-0 p-0 d-flex gap-1">
                    <select class="form-select form-select-sm" v-model="articleState.hide" aria-label=".form-select-sm">
                        <option value="0">공개</option>
                        <option value="1">비공개</option>
                    </select>
                </li>

                <li class="list-group-item border border-0 p-0">
                    <span class="border border-1 p-2 px-3 submit" @click="write">등록</span>
                </li>
            </ul>
        </div>
    </div>
</template>
<script setup lang="ts">
    import { useEditor, EditorContent } from "@tiptap/vue-3";
    import TextAlign from "@tiptap/extension-text-align";
    import StarterKit from "@tiptap/starter-kit";
    import Image from "@tiptap/extension-image";
    import Link from "@tiptap/extension-link";
    import { Highlight } from "@tiptap/extension-highlight";
    import { reactive, ref } from "vue";
    import axios from "@/store/axios";
    import router from "@/router";

    const imgBox = ref<HTMLInputElement>();

    const editor = useEditor({
        content: "",
        extensions: [
            StarterKit,
            TextAlign.configure({
                types: ["heading", "paragraph"],
            }),
            Image.configure({
                inline: true,
            }),
            Highlight.configure({ multicolor: true }),
            Link.configure({
                autolink: true,
                openOnClick: true,
                linkOnPaste: true,

            }),
        ],
    });

    const imgUpload = () => {
        let formData = new FormData();
        if (imgBox.value?.files) {
            formData.append("uploadimg", imgBox.value.files[0]);
        }
        axios.post("/article/admin/images/upload", formData).then((res) => {
            editor.value
                ?.chain()
                .focus()
                .setImage({ src: `./blogapi/article/images/${res.data}` })
                .run();
            articleState.image.push(JSON.parse(JSON.stringify(res.data)));
        });
    };

    const hashStates = reactive<{ warning?: string; tag?: string }>({
        warning: "",
        tag: "",
    });

    let articleState = reactive<{ title: string; tags?: string[]; category: number; hide: number; image: string[] }>({
        title: "",
        tags: [],
        category: 0,
        hide: 0,
        image: [],
    });

    const makingTag = () => {
        if (hashStates.tag?.trim().replace(/ /, "").length == 0) {
            hashStates.warning = "공백은 태그로 사용이 불가능합니다";
            hashStates.tag = "";
            return;
        }
        if (articleState.tags?.includes(hashStates.tag?.trim().replace(/ /, "") as string)) {
            hashStates.warning = "이미 등록된 태그입니다";
            hashStates.tag = "";
            return;
        }
        articleState.tags?.push(hashStates.tag?.trim().replace(/ /, "") as string);
        hashStates.warning = "";
        hashStates.tag = "";
    };

    const deleteTag = (i: number) => {
        articleState.tags?.splice(i, 1);
    };

    const alignment = (which: string) => {
        editor.value?.chain().focus().setTextAlign(which).run();
    };

    const bold = () => {
        editor.value?.chain().focus().toggleBold().run();
    };

    const strike = () => {
        editor.value?.chain().focus().toggleStrike().run();
    };

    const code = () => {
        editor.value?.chain().focus().toggleCode().run();
    };

    const bullet = () => {
        editor.value?.chain().focus().toggleBulletList().run();
    };

    const orderlist = () => {
        editor.value?.chain().focus().toggleOrderedList().run();
    };

    const codeblock = () => {
        editor.value?.chain().focus().toggleCodeBlock().run();
    };

    const clearAll = () => {
        editor.value?.chain().focus().clearNodes().run();
        editor.value?.chain().focus().unsetAllMarks().run();
        editor.value?.chain().focus().unsetTextAlign().run();
    };

    const redo = () => {
        editor.value?.chain().focus().redo().run();
    };

    const undo = () => {
        editor.value?.chain().focus().undo().run();
    };

    const highlight = () => {
        editor.value?.chain().focus().toggleHighlight().run();
    };

    const write = () => {
        if (articleState.category === 0) {
            hashStates.warning = "카테고리를 선택하세요";
            return;
        }
        if (editor.value?.getText().trim().length === 0) {
            hashStates.warning = "본문을 입력하세요";
            return;
        }
        const articlebody: { title: string; context: string | undefined; tags?: string[]; category: number; hide: boolean; menuid: number; image?: string[] } = {
            title: articleState.title,
            context: editor.value?.getHTML(),
            tags: articleState.tags,
            category: articleState.category,
            hide: articleState.hide === 0 ? false : true,
            menuid: articleState.category,
        };
        if (articleState.image.length > 0) {
            articlebody.image = articleState.image;
        }
        axios.post("/article/admin/write", articlebody).then((res) => router.push(`./read?id=${res.data}`));
    };
</script>
<style lang="sass">
    @import "Write.sass"
</style>

// bblogfrontv2nextjs/pages/write.tsx
import { Badge, Button, Flex, Menu, MenuButton, MenuItem, MenuList, Select, Stack, useToast, UseToastOptions } from "@chakra-ui/react";
import { Highlight } from "@tiptap/extension-highlight";
import Image from "@tiptap/extension-image";
import Link from "@tiptap/extension-link";
import Placeholder from "@tiptap/extension-placeholder";
import TextAlign from "@tiptap/extension-text-align";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import { useRouter } from "next/router";
import React, { KeyboardEvent, useRef, useState } from "react";
import { BiAlignLeft, BiAlignMiddle, BiAlignRight, BiBold, BiBrushAlt, BiCodeAlt, BiHeading, BiImage, BiListOl, BiListUl, BiPurchaseTag, BiRedo, BiStrikethrough, BiUnderline, BiUndo } from "react-icons/bi";
import useInput from "../Hook/useInput";
import { write } from "../Store/Async/articleAsync";
import { useAppDispatch } from "../Store/store";
import { articleInfo } from "../Typings/type";
const Write = () => {
    const dispatch = useAppDispatch();
    const router = useRouter();
    const OptionsText = ["INTRO", "FRONTEND", "BACKEND", "ETC", "PORTFOLIO"];
    const imgBox = useRef<HTMLInputElement>(null);
    const [hash, hashOnChange, setHash] = useInput();
    const [options, optionsOnChange] = useInput();
    const [hide, hideOnChange] = useInput();
    const [title, titleOnChange] = useInput();
    const [taglist, setTagList] = useState<string[]>([]);
    const toast = useToast();
    const toastOptions = (desc: string) => {
        return {
            description: desc,
            position: "top",
            status: "error",
            duration: 3000,
            isClosable: true,
        };
    };
    const editor = useEditor({
        extensions: [
            StarterKit.configure({
                heading: {
                    levels: [1, 2, 3],
                },
            }),
            TextAlign.configure({
                types: ["heading", "paragraph"],
            }),
            Image.configure({
                inline: true,
            }),
            Highlight.configure({ multicolor: true }),
            Link.configure({
                autolink: true,
                openOnClick: true,
                linkOnPaste: true,
            }),
            Placeholder.configure({
                placeholder: "내용",
            }),
        ],
        content: "",
    });

    if (!editor) {
        return null;
    }

    const imageUpload = () => {
        let formData = new FormData();
        if (imgBox.current && imgBox.current.files) {
            formData.append("uploadimg", imgBox.current.files[0]);
        }
        // 이미지  redux로 업로드하고난 뒤 파일이름 받아서 아래쪽 src에 넣기
        editor.chain().focus().setImage({ src: `백엔드 만들고 이미지 주소` }).run();
    };

    const alignment = (which: string) => {
        editor.chain().focus().setTextAlign(which).run();
    };
    const bold = () => {
        editor.chain().focus().toggleBold().run();
    };
    const strike = () => {
        editor.chain().focus().toggleStrike().run();
    };
    const bullet = () => {
        editor.chain().focus().toggleBulletList().run();
    };
    const orderlist = () => {
        editor.chain().focus().toggleOrderedList().run();
    };
    const codeblock = () => {
        editor.chain().focus().toggleCodeBlock().run();
    };
    const clearAll = () => {
        editor.chain().focus().clearNodes().run();
        editor.chain().focus().unsetAllMarks().run();
        editor.chain().focus().unsetTextAlign().run();
    };
    const redo = () => {
        editor.chain().focus().redo().run();
    };
    const undo = () => {
        editor.chain().focus().undo().run();
    };

    const highlight = () => {
        editor?.chain().focus().toggleHighlight().run();
    };

    const heading = (i: number) => {
        switch (i) {
            case 0:
                editor.chain().focus().toggleHeading({ level: 1 }).run();
                return;
            case 1:
                editor.chain().focus().toggleHeading({ level: 2 }).run();
                return;
            case 2:
                editor.chain().focus().toggleHeading({ level: 3 }).run();
                return;
            case 3:
                editor.chain().focus().toggleHeading({ level: 4 }).run();
                return;
            default:
                break;
        }
    };

    const setHashtag = (e: KeyboardEvent<HTMLInputElement>) => {
        if (e.key == "Enter" || e.key == ",") {
            if (hash.trim().length == 0) {
                setHash("");
                return;
            }
            if (hash.length > 35) {
                toast(toastOptions("30자 이하로 입력해주세요") as UseToastOptions);
                setHash("");
                return;
            }

            if (taglist.includes(hash)) {
                toast(toastOptions("등록된 태그입니다") as UseToastOptions);
                setHash("");
                return;
            }
            const tag = hash
                .split("")
                .filter((v) => v != ",")
                .join("");
            setTagList([...taglist, tag]);
            setHash("");
        }
    };

    const deleteHashTag = (val: string) => {
        setTagList([...taglist].filter((v) => v != val));
    };

    const writeArticle = () => {
        if (options.length == 0) {
            toast(toastOptions("메뉴를 선택해주세요") as UseToastOptions);
            return;
        }
        if (title.length === 0) {
            toast(toastOptions("제목을 입력해주세요") as UseToastOptions);
            return;
        }
        if (editor.getText().length === 0) {
            toast(toastOptions("내용을 입력해주세요") as UseToastOptions);
            return;
        }
        if (hide.length === 0) {
            toast(toastOptions("공개여부를 선택해주세요") as UseToastOptions);
            return;
        }

        const articleData: articleInfo = {
            menu: OptionsText[options as unknown as number],
            title: title,
            context: editor.getHTML(),
            hashtag: taglist,
            hide: hide == "0" ? false : true,
        };

        dispatch(write(articleData)).then((res) => {
            router.push(`./blog/${res.payload}`);
        });
    };

    return (
        <>
            <Stack padding={1}>
                <Select placeholder="Select option" padding={0} borderRadius={0} value={options} onChange={optionsOnChange}>
                    {OptionsText.map((v, i) => (
                        <option key={i} value={i}>
                            {v}
                        </option>
                    ))}
                </Select>
                <hr />
                <div className="write-title w-screen">
                    <input type="text" name="title" placeholder="제목" className="w-screen" value={title} onChange={titleOnChange} />
                </div>
                <hr />
                <Flex justifyContent={"space-between"} cursor={"pointer"} paddingX={"1rem"}>
                    <BiUndo onClick={() => undo()} />
                    <BiRedo onClick={() => redo()} />
                    <Menu>
                        <MenuButton>
                            <BiHeading />
                        </MenuButton>
                        <MenuList borderWidth={0} minW={"30px"} p={0}>
                            {Array.from({ length: 3 }).map((v, index) => {
                                return (
                                    <MenuItem key={index} onClick={() => heading(index)}>
                                        H{index + 1}
                                    </MenuItem>
                                );
                            })}
                        </MenuList>
                    </Menu>
                    <BiUnderline onClick={() => highlight()} />
                    <BiBold onClick={() => bold()} />
                    <BiStrikethrough onClick={() => strike()} />
                    <BiListUl onClick={() => bullet()} />
                    <BiListOl onClick={() => orderlist} />
                    <BiAlignLeft onClick={() => alignment("left")} />
                    <BiAlignMiddle onClick={() => alignment("center")} />
                    <BiAlignRight onClick={() => alignment("right")} />
                    <BiCodeAlt onClick={() => codeblock()} />
                    <BiBrushAlt onClick={() => clearAll()} />
                    <BiImage
                        onClick={() => {
                            imgBox.current?.click();
                        }}
                    ></BiImage>
                    <input
                        ref={imgBox}
                        type="file"
                        hidden={true}
                        onChange={() => {
                            imageUpload();
                        }}
                    />
                </Flex>
                <hr />
                <EditorContent editor={editor} />
                <hr />
                <div className="write-hashtag w-screen">
                    <input value={hash} onChange={hashOnChange} type="text" name="title" placeholder="태그" className="w-screen" onKeyUp={(e) => setHashtag(e)} />
                </div>
                <hr />
                <Flex gap={3} flexWrap={"wrap"} className="w-100">
                    <BiPurchaseTag className="-scale-x-100" />
                    {taglist.map((v, i) => {
                        return (
                            <Flex key={i} alignItems={"center"} gap={1} maxH={"1rem"}>
                                <Badge key={i} onClick={() => deleteHashTag(v)} cursor={"pointer"}>
                                    {v} x
                                </Badge>
                            </Flex>
                        );
                    })}
                </Flex>
                <Flex gap={2} justifyContent={"flex-end"}>
                    <Select placeholder="공개 설정" padding={0} borderRadius={0} value={hide} onChange={hideOnChange} width={"30%"} maxW={"110px"}>
                        <option value="0">공개</option>
                        <option value="1">비공개</option>
                    </Select>
                    <Button borderWidth={1} borderRadius={0} onClick={writeArticle}>
                        등록
                    </Button>
                </Flex>
            </Stack>
        </>
    );
};

export default Write;
